### ISSUE TITLE
unable to recognize no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by helio-frota** [nodeshift-starters/nodejs-cache#119]

**Comment by lholmquist** [comment]
what version of Openshift are you running on?  and what service was it that returned the error?

**Comment by helio-frota** [comment]
I'm using `CodeReady Containers VM for OpenShift 4.7.11`

When running `oc apply -f service.cache.yml` we can see the error.

It seems to be something related to ` - apiVersion: extensions/v1beta1` that changed to ` - apiVersion: app/v1` or something 
but I'm not sure.

Maybe that needs a double-check and try the new changes :+1:

**Comment by lholmquist** [comment]
> It seems to be something related to - apiVersion: extensions/v1beta1 that changed to - apiVersion: app/v1 or something
but I'm not sure.

I'm bringing up a cluster now,   so i'll see if thats the issue
